workspace:
  base: /go
  path: src/git.maurer-it.net/abaeve/auth-bot

pipeline:
  build:
    image: golang:1.8
    commands:
      - go get -t -v ./...
      - go get github.com/mattn/goveralls
      - goveralls -service=drone.io -ignore=bindata_assetfs.go -repotoken=${REPOTOKEN}
